export interface User {
  _id?: string,
  username?: string,
  email?: string,
  password?: string,
  firstname?: string,
  surname?: string,
  phone?: string,
  address1?: string,
  address2?: string,
  education?: string,
  country?: string,
  state?: string,
  avatar_url?: string,
  avatar_file?: File,
}
